# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Compose Compiler - explicit version (must match kotlin 1.9.22)
android.enableComposeCompilerReports=false
android.enableBuildConfigAsBytecode=false

# Suppress Kotlin version compatibility check
kotlin.suppressKotlinVersionCompatibilityCheck=true